// AUTO-GENERATED by scripts/generate-dino-assets.mjs — do not edit by hand.
// Regenerate with `npm run gen-dino-assets`.
//
// Top-edge silhouettes column-scanned from the rendered brontosaurus PNGs and
// simplified via Ramer–Douglas–Peucker so the Matter.js collider traces the
// visible art exactly without exploding the body count.
//
// MERGED_TOP_EDGE is the per-column min of body and tail (i.e. whichever
// pixel is actually visible in the composited scene). The static collider
// uses this so it follows the back curve where the body dominates and the
// tail-slide where the tail rises above the body's right-curl seam.

export const BODY_TOP_EDGE: ReadonlyArray<readonly [number, number]> = [
  [0, 123],
  [34, 104],
  [89, 86],
  [160, 75],
  [203, 77],
  [256, 89],
  [321, 114],
  [384, 147],
  [460, 196],
  [465, 205],
  [470, 229],
  [471, 474],
  [479, 477],
];

export const TAIL_TOP_EDGE: ReadonlyArray<readonly [number, number]> = [
  [431, 197],
  [437, 178],
  [442, 177],
  [693, 269],
  [850, 334],
  [1144, 466],
  [1176, 482],
  [1192, 492],
  [1196, 497],
];

export const MERGED_TOP_EDGE: ReadonlyArray<readonly [number, number]> = [
  [0, 123],
  [12, 115],
  [49, 98],
  [89, 86],
  [133, 78],
  [185, 75],
  [215, 79],
  [256, 89],
  [298, 104],
  [357, 132],
  [436, 180],
  [438, 177],
  [442, 177],
  [530, 208],
  [649, 252],
  [794, 310],
  [1144, 466],
  [1176, 482],
  [1192, 492],
  [1196, 497],
];

export const BODY_SIZE = { width: 1200, height: 500 } as const;
export const TAIL_SIZE = { width: 1200, height: 500 } as const;
